### ISSUE TITLE
The meaning of value substitions/site in legend 

### ISSUE THREAD

**Issue by huizhen2014** [nselem/EvoDivMet#12]
Hello, I have successfully installed the corason and it looks working well. I found a value in the legend, substituions/site, and I checked all the tutorial and article but can't find the introduction about it.
Could you give a a explanation? Thanks a lot. This software is awesome.

**Comment by nselem** [comment]
Hello, 
Thanks for using CORASON. I'm not sure which value you mention; could you give an example?

**Comment by huizhen2014** [comment]
Thanks, I post a capture on your tutorial website, and using red arrow and frame to highlight it:
![1](https://github.com/nselem/corason/assets/24424074/1641fbee-d35a-4bc8-805e-b6f81907bae8)

**Comment by nselem** [comment]
Oh, I see. That legend comes from [fasttree](http://www.microbesonline.org/fasttree/). CORASON first found the core genes, aligned them with muscle, kept conserved sites with Gblocks, and finally ran Fasttree over these sites.

**Comment by huizhen2014** [comment]
Thanks, and the core genes are searched   based on the genes from reference genome? 😁

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nselem** [comment]
The core genes are searched based on the reference BGC . Its not a full genome but a cluster of genes. Im fact the query gene in fasta is required to assure the core Will not be empty, and World contain at least the query gene and perhaps something else

**Comment by huizhen2014** [comment]
Thanks a lot!😀

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
