### ISSUE TITLE
Problem with Gblocks * File not opened *

### ISSUE THREAD

**Issue by crisdn** [nselem/EvoDivMet#4]
Hello,

I have built the image nselem/corason in my docker running with Windows and executed the example files. I found this problem:

![image](https://user-images.githubusercontent.com/86206320/122687280-e3078880-d215-11eb-9b70-9b9bc3a45d4c.png)

Could you please help me solve this problem?
Thank you in advance.

Best regards.

**Comment by nselem** [comment]
Hello Cris
I have not tried to run it on windows. I can try and we can set a meeting if you wish. Please write to nselem@matmor.unam.mx

**Comment by crisdn** [comment]
Hi nselem,

I have sent you an e-mail. I hope you receive it yesterday.
Thank you.
