### ISSUE TITLE
Empty SVG when run in Singularity

### ISSUE THREAD

**Issue by r-veader** [nselem/EvoDivMet#7]
When running corason in exec mode using singularity, a number of GBlock permission errors appear and the SVG is empty.

`singularity run --bind $PWD:/home/output docker://nselem/corason SSHcorason.pl G6P-isomerase.query RAST.Ids 753783` 
is the command we use. (The use case for singularity is to automate a large number of queries through an iterative script.)

Corason seems to run normally, but starts displaying errors and ultimately, though the output directory looks fully populated, the resulting svg file is empty.

This seems to be the first significant set of errors displayed: 

```
Can't exec "1": No such file or directory at /opt/corason/CORASON/ReadingInputs.pl line 17.
There are 2 similar clusters
Creating query hits tree, without considering the core-clusters

Aligning Sequences 

Shaving alignments with Gblocks
Can't exec "Gblocks": Permission denied at /opt/corason/CORASON/CoreCluster.pl line 123.
Couldn't open /home/output/G6P-isomerase.query-output/PrincipalHits.muscle-gb file No such file or directory at /opt/corason/CORASON/RenamePrincipalHits.pl line 11.
```

The listed 
We've tried this on multiple data sets. 
We have provided a simplified query and a public dataset that reproduces this issue on our system.

Output with errors:
[output.txt](https://github.com/nselem/corason/files/9093455/output.txt)

Query information (all file extensions have .txt added.)
[G6P-isomerase.query.txt](https://github.com/nselem/corason/files/9093456/G6P-isomerase.query.txt)
[RAST.ids.txt](https://github.com/nselem/corason/files/9093460/RAST.ids.txt)
GENOMES/ files:
[753783.fasta.txt](https://github.com/nselem/corason/files/9093479/753783.fasta.txt)
[753783.txt](https://github.com/nselem/corason/files/9093481/753783.txt)
[753861.fasta.txt](https://github.com/nselem/corason/files/9093485/753861.fasta.txt)
[753861.txt](https://github.com/nselem/corason/files/9093487/753861.txt)

Software versions: 
user@server$ cat /etc/*rel*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
user@server:~$ singularity --version
singularity-ce version 3.9.4-focal

Thank You for any assistance!

**Comment by nselem** [comment]
Hello, I have not been successful to put corason on singularity, mainly because of the permission issues with Gblocks, nevertheless, there is a conda beta version, that you may want to try? The repo is here,  https://github.com/miguel-mx/corason-conda I have not update yet the readme, but what you have to do is to create the conda environment with the yml file, and then activate the environment, and use corason.
